version: "3"

services:
  hackathon-nasa: 
    container_name: hackathon-nasa
    build: 
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: always


      